version: '3.6'

networks:
  default: { name: evestidor }

services:

  evestidor-api-gateway:
    image: evestidor/api-gateway:local
    build: ./core-api-gateway
    restart: unless-stopped
    container_name: api-gateway
    volumes:
      - ./core-api-gateway:/app:rw,cached
    environment:
      ENVIRONMENT: localhost
      SECRET_KEY: evestidor-gateway-secret
      STOCK_MANAGER_URL: http://evestidor-stock-manager:8000
